layout_spectrum: 0.25758434762246907
typography_spectrum: 0.24627022934146225
color:
  brandStrength: 0.16745366249233484
  lightness: 0.19037029682658613
  saturation: 0.3928740059491247
  rhythmicContrast: 0.463173491647467
  brandColors:
    - '#595241'
    - '#B8AE9C'
    - '#FFFFFF'
    - '#ACCFCC'
    - '#8A0917'
opengraph:
  type: Post
  appId: ''
author:
  name: Greville Edwards
  email: grev@me.com
  url: GeneralEclectic.eu
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b2863b65-79d3-4e47-8503-51c88d1509ef.png
name: Grevillee
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ed3d7e63-9754-4894-91e0-633c45c39584.png
title: Be Absolute
